name: Check File Extensions

on:
  pull_request:
    paths:
      - '**.py'
      - '**.html'
      - '**.css'
      - '**.java'
      - '**.dart'

jobs:
  check-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for disallowed file extensions
        run: |
          disallowed_files=$(git diff --name-only --diff-filter=ACM origin/main...HEAD | grep -vE '\.(py|html|css|java|dart)$')
          if [ -n "$disallowed_files" ]; then
            echo "Error: The following files have disallowed extensions:"
            echo "$disallowed_files"
            exit 1
          fi
